// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API;

namespace WEB_API.Migrations
{
    [DbContext(typeof(VegaDbContext))]
    [Migration("20190713024523_AddVehicle")]
    partial class AddVehicle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                            .HasAnnotation("ProductVersion", "1.1.1")
                            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEB_API.Models.Feature", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.ToTable("Features");
            });

            modelBuilder.Entity("WEB_API.Models.Make", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.ToTable("Makes");
            });

            modelBuilder.Entity("WEB_API.Models.Model", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<int>("MakeId");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.HasIndex("MakeId");

                b.ToTable("Models");
            });

            modelBuilder.Entity("WEB_API.Models.Vehicle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("ContactEmail")
                    .HasMaxLength(255);

                b.Property<string>("ContactName")
                    .IsRequired()
                    .HasMaxLength(255);

                b.Property<string>("ContactPhone")
                    .IsRequired()
                    .HasMaxLength(255);

                b.Property<bool>("IsRegistered");

                b.Property<DateTime>("LastUpdate");

                b.Property<int>("ModelId");

                b.HasKey("Id");

                b.HasIndex("ModelId");

                b.ToTable("Vehicles");
            });

            modelBuilder.Entity("WEB_API.Models.VehicleFeature", b =>
            {
                b.Property<int>("VehicleId");

                b.Property<int>("FeatureId");

                b.HasKey("VehicleId", "FeatureId");

                b.HasIndex("FeatureId");

                b.ToTable("VehicleFeatures");
            });

            modelBuilder.Entity("WEB_API.Models.Model", b =>
            {
                b.HasOne("WEB_API.Models.Make", "Make")
                    .WithMany("Models")
                    .HasForeignKey("MakeId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("WEB_API.Models.Vehicle", b =>
            {
                b.HasOne("WEB_API.Models.Model", "Model")
                    .WithMany()
                    .HasForeignKey("ModelId")
                    .OnDelete(DeleteBehavior.Cascade);
            });

            modelBuilder.Entity("WEB_API.Models.VehicleFeature", b =>
            {
                b.HasOne("WEB_API.Models.Feature", "Feature")
                    .WithMany()
                    .HasForeignKey("FeatureId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("WEB_API.Models.Vehicle", "Vehicle")
                    .WithMany("Features")
                    .HasForeignKey("VehicleId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
        }
    }
}
